# Generated by Django 5.1.3 on 2024-11-07 09:52

from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_post_created_at'),
    ]
    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='example-slug', unique=True),
            preserve_default=False,
        ),
    ]