# Generated by Django 5.1.3 on 2024-11-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='contact',
            new_name='content',
        ),
    ]
