# Generated by Django 5.1.3 on 2024-11-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Default BIO'),
            preserve_default=False,
        ),
    ]
