# Generated by Django 5.1.3 on 2024-11-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
